import {
  deriveWallsFromRooms,
  exteriorWallFloorSpan,
  parentWallId,
  splitWallsForOpenings,
} from "./derive-walls";
import {
  clampOpeningsInGeometry,
  listOpenings,
  newOpeningId,
  openingsOnSameEdge,
  pushOffsetClearOfOverlaps,
  roomEdge,
} from "./openings";
import {
  clampLabelAnchor,
  defaultLabelAnchor,
} from "./labels";
import {
  isAutoGeneratedRoomName,
  nextAutoRoomName,
  normalizeRoomType,
  roomTypeCategory,
  type PlanRoomType,
} from "./room-types";
import { newStairsId, nextStairRotation, stairsPolygon } from "./stairs";
import {
  EMPTY_GEOMETRY_BOUNDS,
  type FloorGeometry,
  type HingeEnd,
  type PlanDoor,
  type PlanOpening,
  type PlanPoint,
  type PlanRoom,
  type PlanStairs,
  type PlanWindow,
  type StairRotationDeg,
  type SwingSide,
} from "../../types/plan-geometry";

const ROOM_GAP_IN = 36;
const FIRST_ORIGIN: PlanPoint = { x: 48, y: 48 };

export const DEFAULT_DOOR_WIDTH_IN = 32;
export const DEFAULT_WINDOW_WIDTH_IN = 36;
export const DEFAULT_OPENING_WIDTH_IN = 48;
export const DEFAULT_STAIRS_WIDTH_IN = 36;
export const DEFAULT_STAIRS_DEPTH_IN = 96;

function aabb(points: PlanPoint[]): {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
} {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const p of points) {
    minX = Math.min(minX, p.x);
    minY = Math.min(minY, p.y);
    maxX = Math.max(maxX, p.x);
    maxY = Math.max(maxY, p.y);
  }
  return { minX, minY, maxX, maxY };
}

export function recomputeBounds(
  geometry: FloorGeometry,
): FloorGeometry["meta"]["bounds"] {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const consider = (p: PlanPoint) => {
    minX = Math.min(minX, p.x);
    minY = Math.min(minY, p.y);
    maxX = Math.max(maxX, p.x);
    maxY = Math.max(maxY, p.y);
  };

  for (const room of geometry.rooms) {
    for (const p of room.polygon) consider(p);
  }
  for (const wall of geometry.walls) {
    const half = wall.thickness / 2;
    for (const p of wall.centerline) {
      consider({ x: p.x - half, y: p.y - half });
      consider({ x: p.x + half, y: p.y + half });
    }
  }
  for (const stair of geometry.stairs) {
    for (const p of stairsPolygon(stair)) consider(p);
  }

  if (!Number.isFinite(minX)) {
    return { ...EMPTY_GEOMETRY_BOUNDS };
  }
  return { minX, minY, maxX, maxY };
}

function stripLegacyWallIdOpenings(geometry: FloorGeometry): FloorGeometry {
  const isLegacy = (o: { roomId?: string; wallId?: string }) =>
    typeof (o as { wallId?: string }).wallId === "string" &&
    typeof (o as { roomId?: string }).roomId !== "string";

  return {
    ...geometry,
    doors: geometry.doors.filter((d) => !isLegacy(d as never)),
    windows: geometry.windows.filter((w) => !isLegacy(w as never)),
    openings: geometry.openings.filter((o) => !isLegacy(o as never)),
  };
}

/** Normalize room types/categories from the single room-types table. */
export function syncRoomTypes(geometry: FloorGeometry): FloorGeometry {
  let changed = false;
  const rooms = geometry.rooms.map((room) => {
    const type = normalizeRoomType(room.type);
    const category = roomTypeCategory(type);
    if (type !== room.type || category !== room.category) {
      changed = true;
      return { ...room, type, category };
    }
    return room;
  });
  return changed ? { ...geometry, rooms } : geometry;
}

/** Re-derive walls, clamp openings, cut gaps. Always schemaVersion 3. */
export function finalizeGeometry(geometry: FloorGeometry): FloorGeometry {
  const synced = syncRoomTypes(geometry);
  const clamped = clampOpeningsInGeometry({
    ...synced,
    schemaVersion: 3,
  });
  const cuts = listOpenings(clamped).map((o) => ({
    roomId: o.roomId,
    edgeIndex: o.edgeIndex,
    offsetIn: o.offsetIn,
    widthIn: o.widthIn,
  }));
  const baseWalls = deriveWallsFromRooms(clamped.rooms);
  const walls = splitWallsForOpenings(baseWalls, clamped.rooms, cuts);
  const next: FloorGeometry = {
    ...clamped,
    schemaVersion: 3,
    walls,
  };
  return {
    ...next,
    meta: {
      ...next.meta,
      bounds: recomputeBounds(next),
    },
  };
}

/**
 * Migrate older documents to schemaVersion 3 (+ room type normalization).
 * v1: discard per-room wall rings.
 * Legacy wallId openings (none in production) are dropped safely.
 * Legacy type `entry` → `foyer`; categories re-synced from room-types.ts.
 */
export function migrateGeometry(geometry: FloorGeometry): {
  geometry: FloorGeometry;
  didMigrate: boolean;
} {
  let didMigrate = false;
  let doc = geometry;

  if (doc.schemaVersion < 2) {
    doc = { ...doc, walls: [] };
    didMigrate = true;
  }
  if (doc.schemaVersion < 3) {
    doc = stripLegacyWallIdOpenings(doc);
    didMigrate = true;
  }

  const beforeSync = doc;
  doc = syncRoomTypes(doc);
  if (doc !== beforeSync) didMigrate = true;

  const next = finalizeGeometry(doc);
  if (geometry.schemaVersion !== 3) didMigrate = true;
  // Detect type/category fixes that finalize alone would rewrite
  if (JSON.stringify(geometry.rooms) !== JSON.stringify(next.rooms)) {
    didMigrate = true;
  }
  return { geometry: next, didMigrate };
}

function nextRoomNumber(geometry: FloorGeometry): number {
  let max = 0;
  for (const room of geometry.rooms) {
    const match = /^Room\s+(\d+)$/i.exec(room.name);
    if (match) max = Math.max(max, Number(match[1]));
  }
  return max + 1;
}

function nextOrigin(geometry: FloorGeometry): PlanPoint {
  if (geometry.rooms.length === 0) return { ...FIRST_ORIGIN };
  let maxX = -Infinity;
  for (const room of geometry.rooms) {
    for (const p of room.polygon) maxX = Math.max(maxX, p.x);
  }
  return { x: maxX + ROOM_GAP_IN, y: FIRST_ORIGIN.y };
}

function newRoomId(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `room-${Date.now()}`;
}

function buildRectRoom(
  roomId: string,
  name: string,
  origin: PlanPoint,
  widthIn: number,
  depthIn: number,
  existing?: Pick<PlanRoom, "type" | "category">,
): PlanRoom {
  const { x: ox, y: oy } = origin;
  const polygon: PlanPoint[] = [
    { x: ox, y: oy },
    { x: ox + widthIn, y: oy },
    { x: ox + widthIn, y: oy + depthIn },
    { x: ox, y: oy + depthIn },
  ];
  return {
    id: roomId,
    name,
    type: existing?.type ?? "living_room",
    category: existing?.category ?? "living",
    polygon,
    labelAnchor: { x: ox + widthIn / 2, y: oy + depthIn / 2 },
  };
}

export function roomSizeInches(room: PlanRoom): {
  width: number;
  depth: number;
} {
  const box = aabb(room.polygon);
  return { width: box.maxX - box.minX, depth: box.maxY - box.minY };
}

export function roomOrigin(room: PlanRoom): PlanPoint {
  const box = aabb(room.polygon);
  return { x: box.minX, y: box.minY };
}

export function addRectangularRoom(
  geometry: FloorGeometry,
  widthIn: number,
  depthIn: number,
): FloorGeometry {
  const room = buildRectRoom(
    newRoomId(),
    `Room ${nextRoomNumber(geometry)}`,
    nextOrigin(geometry),
    widthIn,
    depthIn,
  );
  return finalizeGeometry({
    ...geometry,
    rooms: [...geometry.rooms, room],
  });
}

export function addRoomAdjoiningWall(
  geometry: FloorGeometry,
  wallId: string,
  widthIn: number,
  depthIn: number,
): FloorGeometry {
  const wall = geometry.walls.find(
    (w) => w.id === wallId || parentWallId(w.id) === parentWallId(wallId),
  );
  if (!wall || wall.kind !== "exterior" || wall.roomIds.length !== 1) {
    return geometry;
  }

  const span = exteriorWallFloorSpan(geometry.rooms, parentWallId(wallId));
  if (!span || span.length < 1e-3) return geometry;

  const { a, b, outward } = span;
  const wallLen = span.length;
  const useWidth = Math.min(widthIn, wallLen);
  const ux = (b.x - a.x) / wallLen;
  const uy = (b.y - a.y) / wallLen;

  const s0 = { x: a.x, y: a.y };
  const s1 = { x: a.x + ux * useWidth, y: a.y + uy * useWidth };
  const n = outward;
  const polygon: PlanPoint[] = [
    s0,
    { x: s0.x + n.x * depthIn, y: s0.y + n.y * depthIn },
    { x: s1.x + n.x * depthIn, y: s1.y + n.y * depthIn },
    s1,
  ];

  const room: PlanRoom = {
    id: newRoomId(),
    name: `Room ${nextRoomNumber(geometry)}`,
    type: "living_room",
    category: "living",
    polygon,
    labelAnchor: {
      x: (s0.x + s1.x) / 2 + (n.x * depthIn) / 2,
      y: (s0.y + s1.y) / 2 + (n.y * depthIn) / 2,
    },
  };

  return finalizeGeometry({
    ...geometry,
    rooms: [...geometry.rooms, room],
  });
}

export function resizeRoom(
  geometry: FloorGeometry,
  roomId: string,
  widthIn: number,
  depthIn: number,
): FloorGeometry {
  const existing = geometry.rooms.find((r) => r.id === roomId);
  if (!existing) return geometry;
  const origin = roomOrigin(existing);
  const room = buildRectRoom(
    roomId,
    existing.name,
    origin,
    widthIn,
    depthIn,
    existing,
  );
  return finalizeGeometry({
    ...geometry,
    rooms: geometry.rooms.map((r) => (r.id === roomId ? room : r)),
  });
}

export function translateRoom(
  geometry: FloorGeometry,
  roomId: string,
  dx: number,
  dy: number,
): FloorGeometry {
  if (dx === 0 && dy === 0) return geometry;
  const shift = (p: PlanPoint): PlanPoint => ({ x: p.x + dx, y: p.y + dy });
  return finalizeGeometry({
    ...geometry,
    rooms: geometry.rooms.map((r) =>
      r.id === roomId
        ? {
            ...r,
            polygon: r.polygon.map(shift),
            labelAnchor: shift(r.labelAnchor),
          }
        : r,
    ),
  });
}

export function deleteRoom(
  geometry: FloorGeometry,
  roomId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    rooms: geometry.rooms.filter((r) => r.id !== roomId),
    doors: geometry.doors.filter((d) => d.roomId !== roomId),
    windows: geometry.windows.filter((w) => w.roomId !== roomId),
    openings: geometry.openings.filter((o) => o.roomId !== roomId),
  });
}

/**
 * Set room type. Auto-updates the name unless the current name looks custom
 * (does not match the auto pattern for the previous type).
 */
export function setRoomType(
  geometry: FloorGeometry,
  roomId: string,
  type: PlanRoomType,
): FloorGeometry {
  const room = geometry.rooms.find((r) => r.id === roomId);
  if (!room) return geometry;
  const nextType = normalizeRoomType(type);
  const keepName = !isAutoGeneratedRoomName(room.name, room.type);
  const name = keepName
    ? room.name
    : nextAutoRoomName(geometry.rooms, nextType, roomId);
  return finalizeGeometry({
    ...geometry,
    rooms: geometry.rooms.map((r) =>
      r.id === roomId
        ? {
            ...r,
            type: nextType,
            category: roomTypeCategory(nextType),
            name,
          }
        : r,
    ),
  });
}

/** Free-text name override — survives later type changes. */
export function setRoomName(
  geometry: FloorGeometry,
  roomId: string,
  name: string,
): FloorGeometry {
  const trimmed = name.trim();
  if (!trimmed) return geometry;
  return finalizeGeometry({
    ...geometry,
    rooms: geometry.rooms.map((r) =>
      r.id === roomId ? { ...r, name: trimmed } : r,
    ),
  });
}

export function setRoomLabelAnchor(
  geometry: FloorGeometry,
  roomId: string,
  anchor: PlanPoint,
): FloorGeometry {
  const room = geometry.rooms.find((r) => r.id === roomId);
  if (!room) return geometry;
  const labelAnchor = clampLabelAnchor(room, anchor);
  if (
    Math.abs(labelAnchor.x - room.labelAnchor.x) < 1e-9 &&
    Math.abs(labelAnchor.y - room.labelAnchor.y) < 1e-9
  ) {
    return geometry;
  }
  return {
    ...geometry,
    rooms: geometry.rooms.map((r) =>
      r.id === roomId ? { ...r, labelAnchor } : r,
    ),
  };
}

export function resetRoomLabelAnchor(
  geometry: FloorGeometry,
  roomId: string,
): FloorGeometry {
  const room = geometry.rooms.find((r) => r.id === roomId);
  if (!room) return geometry;
  const labelAnchor = defaultLabelAnchor(room);
  if (
    Math.abs(labelAnchor.x - room.labelAnchor.x) < 1e-9 &&
    Math.abs(labelAnchor.y - room.labelAnchor.y) < 1e-9
  ) {
    return geometry;
  }
  return {
    ...geometry,
    rooms: geometry.rooms.map((r) =>
      r.id === roomId ? { ...r, labelAnchor } : r,
    ),
  };
}

export function canAdjoinWall(
  geometry: FloorGeometry,
  wallId: string,
): boolean {
  const wall = geometry.walls.find(
    (w) => w.id === wallId || parentWallId(w.id) === parentWallId(wallId),
  );
  return Boolean(wall && wall.kind === "exterior" && wall.roomIds.length === 1);
}

/** Map a wall hit to the room-edge used for placing openings. */
export function wallToRoomEdge(
  geometry: FloorGeometry,
  wallId: string,
): { roomId: string; edgeIndex: number; spanOffsetIn: number; spanLengthIn: number } | null {
  const wall = geometry.walls.find((w) => w.id === wallId);
  if (!wall || wall.roomIds.length === 0) return null;

  const base = parentWallId(wallId);
  if (base.startsWith("we:")) {
    const parts = base.split(":");
    const edgeIndex = Number(parts[parts.length - 2]);
    const roomId = parts.slice(1, -2).join(":");
    const room = geometry.rooms.find((r) => r.id === roomId);
    if (!room || !Number.isFinite(edgeIndex)) return null;
    const edge = roomEdge(room, edgeIndex);
    if (!edge) return null;
    // Span may be a remainder — approximate offset from floor span start
    const span = exteriorWallFloorSpan(geometry.rooms, base);
    if (!span) {
      return { roomId, edgeIndex, spanOffsetIn: 0, spanLengthIn: edge.length };
    }
    const along = Math.hypot(span.a.x - edge.a.x, span.a.y - edge.a.y);
    return {
      roomId,
      edgeIndex,
      spanOffsetIn: along,
      spanLengthIn: span.length,
    };
  }

  // Interior: pick first room id; find edge collinear with wall centerline
  if (wall.centerline.length < 2) return null;
  const c0 = wall.centerline[0];
  const c1 = wall.centerline[1];
  for (const roomId of wall.roomIds) {
    const room = geometry.rooms.find((r) => r.id === roomId);
    if (!room) continue;
    for (let i = 0; i < room.polygon.length; i += 1) {
      const edge = roomEdge(room, i);
      if (!edge) continue;
      const sameH =
        Math.abs(edge.a.y - edge.b.y) < 1e-6 &&
        Math.abs(c0.y - c1.y) < 1e-6 &&
        Math.abs(edge.a.y - c0.y) < 1e-6;
      const sameV =
        Math.abs(edge.a.x - edge.b.x) < 1e-6 &&
        Math.abs(c0.x - c1.x) < 1e-6 &&
        Math.abs(edge.a.x - c0.x) < 1e-6;
      if (!sameH && !sameV) continue;
      const t0 = sameH
        ? Math.min(c0.x, c1.x) - Math.min(edge.a.x, edge.b.x)
        : Math.min(c0.y, c1.y) - Math.min(edge.a.y, edge.b.y);
      // Orient from edge.a
      const startAlong = sameH
        ? (edge.b.x >= edge.a.x
            ? Math.min(c0.x, c1.x) - edge.a.x
            : edge.a.x - Math.max(c0.x, c1.x))
        : edge.b.y >= edge.a.y
          ? Math.min(c0.y, c1.y) - edge.a.y
          : edge.a.y - Math.max(c0.y, c1.y);
      const spanLen = Math.hypot(c1.x - c0.x, c1.y - c0.y);
      void t0;
      return {
        roomId,
        edgeIndex: i,
        spanOffsetIn: Math.max(0, startAlong),
        spanLengthIn: spanLen,
      };
    }
  }
  return null;
}

function placeOpeningOffset(
  geometry: FloorGeometry,
  roomId: string,
  edgeIndex: number,
  widthIn: number,
  preferredOffset: number,
): number | null {
  const room = geometry.rooms.find((r) => r.id === roomId);
  if (!room) return null;
  const edge = roomEdge(room, edgeIndex);
  if (!edge) return null;
  const others = openingsOnSameEdge(geometry, roomId, edgeIndex);
  return pushOffsetClearOfOverlaps(
    preferredOffset,
    widthIn,
    edge.length,
    others,
  );
}

export function addDoorOnWall(
  geometry: FloorGeometry,
  wallId: string,
  preferredOffsetAlongSpan?: number,
): FloorGeometry {
  const mapped = wallToRoomEdge(geometry, wallId);
  if (!mapped) return geometry;
  const width = DEFAULT_DOOR_WIDTH_IN;
  const preferred =
    preferredOffsetAlongSpan !== undefined
      ? mapped.spanOffsetIn + preferredOffsetAlongSpan - width / 2
      : mapped.spanOffsetIn + mapped.spanLengthIn / 2 - width / 2;
  const offset = placeOpeningOffset(
    geometry,
    mapped.roomId,
    mapped.edgeIndex,
    width,
    preferred,
  );
  if (offset === null) return geometry;
  const door: PlanDoor = {
    id: newOpeningId("door"),
    roomId: mapped.roomId,
    edgeIndex: mapped.edgeIndex,
    offsetIn: offset,
    widthIn: width,
    hingeEnd: "start",
    swingSide: 1,
  };
  return finalizeGeometry({
    ...geometry,
    doors: [...geometry.doors, door],
  });
}

export function addWindowOnWall(
  geometry: FloorGeometry,
  wallId: string,
  preferredOffsetAlongSpan?: number,
): FloorGeometry {
  const mapped = wallToRoomEdge(geometry, wallId);
  if (!mapped) return geometry;
  const width = DEFAULT_WINDOW_WIDTH_IN;
  const preferred =
    preferredOffsetAlongSpan !== undefined
      ? mapped.spanOffsetIn + preferredOffsetAlongSpan - width / 2
      : mapped.spanOffsetIn + mapped.spanLengthIn / 2 - width / 2;
  const offset = placeOpeningOffset(
    geometry,
    mapped.roomId,
    mapped.edgeIndex,
    width,
    preferred,
  );
  if (offset === null) return geometry;
  const win: PlanWindow = {
    id: newOpeningId("win"),
    roomId: mapped.roomId,
    edgeIndex: mapped.edgeIndex,
    offsetIn: offset,
    widthIn: width,
  };
  return finalizeGeometry({
    ...geometry,
    windows: [...geometry.windows, win],
  });
}

export function addOpeningOnWall(
  geometry: FloorGeometry,
  wallId: string,
  preferredOffsetAlongSpan?: number,
): FloorGeometry {
  const mapped = wallToRoomEdge(geometry, wallId);
  if (!mapped) return geometry;
  const width = DEFAULT_OPENING_WIDTH_IN;
  const preferred =
    preferredOffsetAlongSpan !== undefined
      ? mapped.spanOffsetIn + preferredOffsetAlongSpan - width / 2
      : mapped.spanOffsetIn + mapped.spanLengthIn / 2 - width / 2;
  const offset = placeOpeningOffset(
    geometry,
    mapped.roomId,
    mapped.edgeIndex,
    width,
    preferred,
  );
  if (offset === null) return geometry;
  const opening: PlanOpening = {
    id: newOpeningId("open"),
    roomId: mapped.roomId,
    edgeIndex: mapped.edgeIndex,
    offsetIn: offset,
    widthIn: width,
  };
  return finalizeGeometry({
    ...geometry,
    openings: [...geometry.openings, opening],
  });
}

export function moveOpening(
  geometry: FloorGeometry,
  openingId: string,
  newOffsetIn: number,
): FloorGeometry {
  const update = <T extends { id: string; roomId: string; edgeIndex: number; offsetIn: number; widthIn: number }>(
    items: T[],
  ): T[] =>
    items.map((item) => {
      if (item.id !== openingId) return item;
      const room = geometry.rooms.find((r) => r.id === item.roomId);
      if (!room) return item;
      const edge = roomEdge(room, item.edgeIndex);
      if (!edge) return item;
      const others = openingsOnSameEdge(
        geometry,
        item.roomId,
        item.edgeIndex,
        openingId,
      );
      const pushed = pushOffsetClearOfOverlaps(
        newOffsetIn,
        item.widthIn,
        edge.length,
        others,
      );
      if (pushed === null) return item;
      return { ...item, offsetIn: pushed };
    });

  return finalizeGeometry({
    ...geometry,
    doors: update(geometry.doors),
    windows: update(geometry.windows),
    openings: update(geometry.openings),
  });
}

export function setOpeningWidth(
  geometry: FloorGeometry,
  openingId: string,
  widthIn: number,
): FloorGeometry {
  const update = <T extends { id: string; roomId: string; edgeIndex: number; offsetIn: number; widthIn: number }>(
    items: T[],
  ): T[] =>
    items.map((item) => {
      if (item.id !== openingId) return item;
      const room = geometry.rooms.find((r) => r.id === item.roomId);
      if (!room) return item;
      const edge = roomEdge(room, item.edgeIndex);
      if (!edge) return item;
      const others = openingsOnSameEdge(
        geometry,
        item.roomId,
        item.edgeIndex,
        openingId,
      );
      const pushed = pushOffsetClearOfOverlaps(
        item.offsetIn,
        widthIn,
        edge.length,
        others,
      );
      if (pushed === null) return item;
      return { ...item, offsetIn: pushed, widthIn };
    });

  return finalizeGeometry({
    ...geometry,
    doors: update(geometry.doors),
    windows: update(geometry.windows),
    openings: update(geometry.openings),
  });
}

export function deleteOpening(
  geometry: FloorGeometry,
  openingId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    doors: geometry.doors.filter((d) => d.id !== openingId),
    windows: geometry.windows.filter((w) => w.id !== openingId),
    openings: geometry.openings.filter((o) => o.id !== openingId),
  });
}

export function flipDoorSwing(
  geometry: FloorGeometry,
  doorId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    doors: geometry.doors.map((d) =>
      d.id === doorId
        ? { ...d, swingSide: (-d.swingSide) as SwingSide }
        : d,
    ),
  });
}

export function flipDoorHinge(
  geometry: FloorGeometry,
  doorId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    doors: geometry.doors.map((d) =>
      d.id === doorId
        ? {
            ...d,
            hingeEnd: (d.hingeEnd === "start" ? "end" : "start") as HingeEnd,
          }
        : d,
    ),
  });
}

export function addStairs(geometry: FloorGeometry): FloorGeometry {
  let origin = { ...FIRST_ORIGIN };
  if (geometry.rooms.length > 0 || geometry.stairs.length > 0) {
    let maxX = -Infinity;
    for (const room of geometry.rooms) {
      for (const p of room.polygon) maxX = Math.max(maxX, p.x);
    }
    for (const s of geometry.stairs) {
      for (const p of stairsPolygon(s)) maxX = Math.max(maxX, p.x);
    }
    origin = { x: maxX + ROOM_GAP_IN, y: FIRST_ORIGIN.y };
  }
  const stair: PlanStairs = {
    id: newStairsId(),
    origin,
    widthIn: DEFAULT_STAIRS_WIDTH_IN,
    depthIn: DEFAULT_STAIRS_DEPTH_IN,
    rotationDeg: 0,
    direction: "up",
  };
  return finalizeGeometry({
    ...geometry,
    stairs: [...geometry.stairs, stair],
  });
}

export function translateStairs(
  geometry: FloorGeometry,
  stairsId: string,
  dx: number,
  dy: number,
): FloorGeometry {
  if (dx === 0 && dy === 0) return geometry;
  return finalizeGeometry({
    ...geometry,
    stairs: geometry.stairs.map((s) =>
      s.id === stairsId
        ? {
            ...s,
            origin: { x: s.origin.x + dx, y: s.origin.y + dy },
          }
        : s,
    ),
  });
}

export function resizeStairs(
  geometry: FloorGeometry,
  stairsId: string,
  widthIn: number,
  depthIn: number,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    stairs: geometry.stairs.map((s) =>
      s.id === stairsId ? { ...s, widthIn, depthIn } : s,
    ),
  });
}

export function rotateStairs(
  geometry: FloorGeometry,
  stairsId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    stairs: geometry.stairs.map((s) =>
      s.id === stairsId
        ? { ...s, rotationDeg: nextStairRotation(s.rotationDeg) }
        : s,
    ),
  });
}

export function toggleStairsDirection(
  geometry: FloorGeometry,
  stairsId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    stairs: geometry.stairs.map((s) =>
      s.id === stairsId
        ? { ...s, direction: s.direction === "up" ? "down" : "up" }
        : s,
    ),
  });
}

export function deleteStairs(
  geometry: FloorGeometry,
  stairsId: string,
): FloorGeometry {
  return finalizeGeometry({
    ...geometry,
    stairs: geometry.stairs.filter((s) => s.id !== stairsId),
  });
}

export type { StairRotationDeg };
